flowchart LR
    subgraph Application
        vp[VideoProcessor]
        fd[FallDetector]
        mm[ModelManager]
        fe[FeatureExtractor]
        am[AudioManager]
    end
    vp --> fd
    fd --> mm
    fd --> fe
    fd --> am
